---
- name: A playbook useing fetch module
  hosts: bender
  connection: ssh   # use the connection plugin, ssh.py (this is the default)
  gather_facts: no   # no need to define ansible_facts in this playbook

  tasks:
  - name: "Copy files from remote to local"
    fetch:
      src: /tmp/bender.file
      dest: /tmp/bender.file
      flat: yes
